### PR TITLE
Changed luasocket module loading

### PR DESCRIPTION
**Pull request by Lixquid**
Checking if a module exists via the filesystem is generally a bad idea; newer modules are typically named differently, or may be reimplemented as a lua module which wraps another module.

A better way is to (safely) attempt to load a generically named module, test if it contains the functions we need, and then fail safely.

### CODE REVIEW

**Comment by Noiwex** [comment]
Otherwise it would error even with pcall.

```
] lua pcall(require, "invalid")
Couldn't include file 'includes\modules\invalid.lua' (File not found) (<nowhere>)
Player [66][Noiwex] ERR: Couldn't include file 'includes\modules\invalid.lua' (File not found) (<nowhere>)
```

**Comment by Lixquid** [comment]
While it does print an error to the console, it doesn't halt execution, and it still returns the correct values;

```
] lua ok, no = pcall( require, "nothing" ) print( ok, no )
Couldn't include file 'includes\modules\nothing.lua' (File not found) (<nowhere>)
false	Module not found!
```

It comes down to the benefits of requiring the module freely versus not double printing the "module not found" error to the console

**Comment by Noiwex** [comment]
epoe spam gee thanks

**Comment by Lixquid** [comment]
Pcalled `require`s that fail don't trigger entries in EPOE

**Comment by Python1320** [comment]
Last time I checked they do

**Comment by Noiwex** [comment]
It's conflicting now and someone has already changed it somehow.

**Pull request closed without merging**
